services:
  app:
    build:
      context: .
      target: prod
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HOST: 0.0.0.0

  app-dev:
    build:
      context: .
      target: dev
    ports:
      - 3001:3000
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      FORCE_COLOR: 1
    volumes:
      - ./:/app
    tty: false
    stdin_open: false
